//import './styles/globals.css';
'use client';
import GlobalStyles from './styles/GlobalStyles';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
